contact/urls.py
from django.conf.urls import url
from django.urls import path
from contact.views import Contact_list,delcontacts,Contact_forms


app_name='contact'
urlpatterns = [
    url(r'^contact_list/$', Contact_list, name='contact_list'),
    #url(r'^memo_list/(?P<memo_id>\d+)/$', Memo_detail, name="detail_memo"),
    url(r'^contact_form/$', Contact_forms, name='contact_form'),
    url(r'^delcontact/$',delcontacts,name='delcontact'),
]

image/urls.py
from django.conf.urls import url
from django.urls import path
from image.views import Image_list,Image_forms,delimages


app_name='image'
urlpatterns = [
    url(r'^image_list/$', Image_list, name='image_list'),
    url(r'^image_form/$', Image_forms, name='image_form'),
    url(r'^delimage/$',delimages,name='delimage'),
]

memo/urls.py
from django.conf.urls import url
from django.urls import path
from memo.views import Memo_list,Memo_detail,Memo_forms,delmemos


app_name='memo'
urlpatterns = [
    url(r'^memo_list/$', Memo_list, name='memo_list'),
    url(r'^memo_list/(?P<memo_id>\d+)/$', Memo_detail, name="detail_memo"),
    url(r'^memo_form/$', Memo_forms, name='memo_form'),
    url(r'^delmemo/$',delmemos,name='delmemo'),
]

password/urls.py
from django.conf.urls import url
from django.urls import path
from password.views import Password_list,Password_detail,Password_forms,index,delpasswords


app_name='password'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^password/$', Password_list, name='password'),
    url(r'^password/(?P<password_id>\d+)/$', Password_detail, name="detail_password"),
    url(r'^password_form/$', Password_forms, name='password_form'),
    url(r'^delpassword/$',delpasswords,name='delpassword'),
]

project/urls.py
from django.conf.urls.static import static
from project.settings import MEDIA_ROOT
import xadmin
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from dailyreport import views
from login import views as view
urlpatterns = [
    path('',include('contact.urls')),
    path('',include('image.urls')),
    path('',include('password.urls')),
    path('',include('memo.urls'),),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
    url(r'^xadmin/', xadmin.site.urls, name='xadmin'),
    url(r'media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    path('admin/', admin.site.urls),

    url(r'^login/', view.login),
    url(r'^register/', view.register),
    url(r'^logout/', view.logout),
    url(r'^captcha', include('captcha.urls')),
    url(r'^confirm/$', view.user_confirm),

    url(r'^myreport/$', views.MyReportView.as_view(), name='myreport'),
    url(r'^myreport/create$', views.ReportCreateView.as_view(), name='myreport-create'),
    url(r'^myreport/detail$', views.ReportDetailView.as_view(), name='myreport-detail'),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    SEX_BOY = 1
    SEX_GIRL = 0
    SEX_ITEMS = (
        (SEX_BOY, '男'),
        (SEX_GIRL, '女'),
    )
    name=models.CharField(max_length=25,verbose_name="姓名")
    relation=models.CharField(max_length=30,verbose_name="关系")
    email=models.EmailField(verbose_name="Email")
    phone=models.CharField(max_length=12,verbose_name="手机号")
    word=models.CharField(max_length=50,verbose_name="职业")
    sex=models.PositiveIntegerField(default=SEX_BOY, choices=SEX_ITEMS, verbose_name="性别")
    created_time=models.DateTimeField(auto_now_add=True,editable=False,verbose_name="创建时间")

    class Meta:
        verbose_name=verbose_name_plural="联系人管理"
        ordering = ['-id']

login/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    gender=(
        ('male','男'),
        ('female','女'),
    )

    name=models.CharField(max_length=128,unique=True)
    password=models.CharField(max_length=256)
    email=models.EmailField(unique=True)
    sex=models.CharField(max_length=32,choices=gender,default="男")
    c_time=models.DateTimeField(auto_now_add=True)
    #新增了has_confirmed字段，这是个布尔值，默认为False，也就是未进行邮件注册；
    has_confirmed = models.BooleanField(default=False)
    def __str__(self):
        return self.name

    class Meta:
        ordering=["-c_time"]
        verbose_name="使用者"
        verbose_name_plural="使用者"


class ConfirmString(models.Model):
    '''
    ConfirmString模型保存了用户和注册码之间的关系，一对一的形式；
    '''
    #code字段是哈希后的注册码；
    code = models.CharField(max_length=256)
    user = models.OneToOneField('User', on_delete=models.CASCADE, )
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name + ":   " + self.code

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "确认码"
        verbose_name_plural = "确认码"

memo/models.py
from django.db import models
from stdimage.models import StdImageField
# Create your models here.
from DjangoUeditor.models import UEditorField

class Category(models.Model):
    name = models.CharField(max_length=10, verbose_name="名称")

    class Meta:
        verbose_name = verbose_name_plural = '分类'
    def __str__(self):
        return self.name




class Memo(models.Model):
    title=models.TextField(max_length=360,verbose_name='标题',default='生活')
    content=UEditorField(width=600, height=300, toolbars="full", imagePath="images/", filePath="files/",
                         upload_settings={"imageMaxSize":12040000},
                         settings={}, verbose_name='内容')
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, editable=False, verbose_name="创建时间")
    image2 = StdImageField(
        upload_to='image/%Y/%m', variations={'thumbnail': {'width': 100, 'height': 75}},
        verbose_name=u"图片",
    )

    class Meta:
        verbose_name = verbose_name_plural = '便签'
        ordering=['-id']

    def image_img2(self):
        if self.image2:
            return str('<img src="%s" />' % self.image2.thumbnail.url)
        else:
            return '上传图片'

    image_img2.short_description = '图片'
    image_img2.allow_tags = True  # 列表页显示图片

password/models.py
from django.db import models
from stdimage.models import StdImageField
# Create your models here.
class Password(models.Model):
    appname=models.CharField(max_length=25,verbose_name="备注")
    user=models.CharField(max_length=30,verbose_name="用户名")
    email=models.EmailField(verbose_name="Email")
    phone=models.CharField(max_length=12,verbose_name="手机号")
    password=models.CharField(max_length=50,verbose_name="密码")
    created_time=models.DateTimeField(auto_now_add=True,editable=False,verbose_name="创建时间")
    image1 = StdImageField(
        upload_to='image/%Y/%m', variations={'thumbnail': {'width': 100, 'height': 75}},
        verbose_name=u"图片",
        )

    class Meta:
        verbose_name=verbose_name_plural="密码管理"
        ordering = ['-id']
    def image_img1(self):
        if self.image1:
            return str('<img src="%s" />' % self.image1.thumbnail.url)
        else:
            return '上传图片'

    image_img1.short_description = '图片'
    image_img1.allow_tags = True  # 列表页显示图片

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):

    class Meta:
        model=Contact
        fields=(
            'name','word','relation','phone','email','sex'
        )

image/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):


    class Meta:
        model=Image
        fields=(
            'image3',
        )

contact/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import ContactForm
from .models import Contact
from django.shortcuts import get_object_or_404
# Create your views here.
def Contact_list(request):

    contact=Contact.objects.all()
    return render(request, 'contact_list.html', context={'contacts':contact})



def delcontacts(request):

    id = request.GET.get("id")
    Contact.objects.filter(id=id).delete()
    return redirect('/contact_list/')

def Contact_forms(request):
    contact = Contact.objects.all()
    if request.method == 'POST':
        form = ContactForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/contact_list/')
    else:
        form = ContactForm()
    context = {
        'contacts': contact,
        'form': form,
    }
    return render(request, 'contact_form.html', context=context)

image/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect

from .forms import ImageForm
from .models import Image
from django.shortcuts import get_object_or_404

# Create your views here.
def Image_list(request):
    images=Image.objects.all()
    return render(request, 'image_list.html', context={'images':images})


def Image_forms(request):
    image = Image.objects.all()
    if request.method == 'POST':
        form = ImageForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/image_list/')
    else:
        form = ImageForm()
    context = {
        'memos': image,
        'form': form,
    }
    return render(request, 'image_form.html', context=context)


def delimages(request):
    id = request.GET.get("id")
    Image.objects.filter(id=id).delete()

    return redirect('/image_list/')

login/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from . import models
from django import forms
from login import forms
from django.conf import settings
# Create your views here.
import hashlib
import datetime

def hash_code(s, salt='mysite'):  # 加点盐
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()

def make_confirm_string(user):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_code(user.name, now)
    models.ConfirmString.objects.create(code=code, user=user,)
    return code


def send_email(email, code):
    from django.core.mail import EmailMultiAlternatives

    subject = '来自事务管理系统的注册确认邮件'

    text_content = '''感谢注册事务管理系统，专注于个人事务的管理！\
                    如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！'''

    html_content = '''
                    <p>感谢注册<a href="http://{}/confirm/?code={}" target=blank>事务管理系统</a>，\
                    专注于个人事务的管理！</p>
                    <p>请点击站点链接完成注册确认！</p>
                    <p>此链接有效期为{}天！</p>
                    '''.format('127.0.0.1:8000', code, settings.CONFIRM_DAYS)

    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


def index(request):
    return render(request,'index.html')

def login(request):
    message=""
    if request.session.get('is_login', None):
        return redirect("/")
    if request.method == "POST":
        login_form = forms.UserForm(request.POST)
        message = "请检查填写的内容！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                user = models.User.objects.get(name=username)
                if not user.has_confirmed:
                    message = "该用户还未通过邮件确认！"
                    return render(request, 'login.html', {'message':message})
                if user.password == hash_code(password):  # 哈希值和数据库内的值进行比对
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return redirect('index.html')
                else:
                    message = "密码不正确！"
            except:
                message = "用户不存在！"
        return render(request, 'login.html', {'message':message})

    login_form = forms.UserForm()
    return render(request, 'login.html', {'message':message, 'login_form':login_form})


def register(request):
    message = ""
    if request.session.get('is_login', None):
        # 登录状态不允许注册。你可以修改这条原则！
        return redirect("/")
    if request.method == "POST":
        register_form = forms.RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():  # 获取数据
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return render(request, 'register.html', {'message':message})
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return render(request, 'register.html', {'message':message})
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'register.html', {'message':message})

                # 当一切都OK的情况下，创建新用户

                new_user = models.User()
                new_user.name = username
                new_user.password = hash_code(password1)  # 使用加密密码
                new_user.email = email
                new_user.sex = sex
                new_user.save()

                code = make_confirm_string(new_user)
                send_email(email, code)
                message = '请前往注册邮箱，进行邮件确认！'
                return render(request, 'confirm.html', {'message':message})  # 跳转到等待邮件确认页面。
    register_form = forms.RegisterForm()
    return render(request, 'register.html', {'message':message, 'register_form':register_form})

def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/")
    request.session.flush()
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/")


def user_confirm(request):
    code = request.GET.get('code', None)
    message = ''
    try:
        confirm = models.ConfirmString.objects.get(code=code)
    except:
        message = '无效的确认请求!'
        return render(request, 'confirm.html', {'message':message})

    c_time = confirm.c_time
    now = datetime.datetime.now()
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = '您的邮件已经过期！请重新注册!'
        return render(request, 'confirm.html', {'message':message})
    else:
        confirm.user.has_confirmed = True
        confirm.user.save()
        confirm.delete()
        message = '感谢确认，请使用账户登录！'
        return render(request, 'confirm.html', {'message':message})

memo/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import MemoForm
from .models import Memo
from django.shortcuts import get_object_or_404
from django.forms import forms
#from DjangoUeditor.forms import UEditorField
# Create your views here.




def Memo_list(request):
    memo=Memo.objects.all()
    return render(request, 'memo_list.html', context={'memos':memo})


def Memo_detail(request,memo_id):
    detail_memos=get_object_or_404(Memo,pk=memo_id)

    return render(request,'memo_detail.html',context={'detail_memos':detail_memos})


def Memo_forms(request):
    memo = Memo.objects.all()
    if request.method == 'POST':
        form = MemoForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/memo_list/')
    else:
        form = MemoForm()
    context = {
        'memos': memo,
        'form': form,
    }

    return render(request, 'memo_form.html', context=context)



def delmemos(request):
    id = request.GET.get("id")
    Memo.objects.filter(id=id).delete()

    return redirect('/memo_list/')

password/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import PasswordForm
from memo.models import Memo
from .models import Password
from image.models import Image
from django.shortcuts import get_object_or_404
# Create your views here.


def index(request):
    password = Password.objects.all()
    passwords=password[0:2]

    memo = Memo.objects.all()
    memos = memo[0:2]

    image=Image.objects.all()
    images = image[0:6]
    return render(request,'index.html',context={'passwords': passwords,'memos':memos,'images':images})


def Password_list(request):
    password=Password.objects.all()
    return render(request, 'password.html', context={'passwords':password})


def Password_detail(request,password_id):
    detail_passwords=get_object_or_404(Password,pk=password_id)
    return render(request,'password_detail.html',context={'detail_passwords':detail_passwords})


def Password_forms(request):
    password = Password.objects.all()
    if request.method == 'POST':
        form = PasswordForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/password/')
    else:
        form = PasswordForm()
    context = {
        'passwords': password,
        'form': form,
    }
    return render(request, 'password_form.html', context=context)


def delpasswords(request):
    id = request.GET.get("id")
    Password.objects.filter(id=id).delete()

    return redirect('/password/')

templates/contact_form.html
{% extends "./index.html" %}
{% load static %}



{% block main %}
<div class="card col-8">

<div class="jumbotron jumbotron-fluid"style="background-color: cornflowerblue;margin-top: 10px;">
    <h2 class="display-4">添加联系人</h2>
  </div>
    <form method="post" enctype="multipart/form-data">
{{ form.non_field_errors }}
        {% csrf_token %}
 <div class="fieldWrapper form-group">
        {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}"><h4>Name:</h4></label>
        <input  class="form-control" placeholder="Enter name" type="text" id="id_name" name="name">
        </div>

        <div class="fieldWrapper form-group">
        {{ form.relation.errors }}
            <label for="{{ form.relation.id_for_label }}"><h4>Relation:</h4></label>
        <input  class="form-control" placeholder="Enter relation" type="text" id="id_relation" name="relation">
        </div>

    <div class="fieldWrapper form-group">
    {{ form.word.errors }}
        <label for="{{ form.word.id_for_label }}"><h4>Word:</h4></label>
     <input  class="form-control" placeholder="Enter Word" type="text" id="id_word" name="word">
</div>
    <div class="fieldWrapper form-group">
    {{ form.phone.errors }}
        <label for="{{ form.phone.id_for_label }}"><h4>Phone:</h4></label>
    <input  class="form-control" placeholder="Enter Phone" type="text" id="id_phone" name="phone">
</div>
    <div class="fieldWrapper form-group">
    {{ form.email.errors }}

        <label for="{{ form.eamil.id_for_label }}"><h4>Email:</h4></label>
        <div class="input-group-prepend">
          <div class="input-group-text">@</div>
            <input  class="form-control" placeholder="name@example.com" type="email" id="id_email" name="email">
        </div>
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
</div>
    <div class="fieldWrapper form-group">
    {{ form.sex.errors }}
     <label for="{{ form.sex.id_for_label }}"><h5>性别:</h5></label>
     <div class="input-group-prepend">
    {{ form.sex }}
     </div>
</div>
        <button type="submit" class="btn btn-primary"style="float: right;">Submit</button>
          </form>


</div>


{% endblock %}

templates/contact_list.html
{% extends "./index.html" %}
{% load static %}


{% block main %}

<div class="card col-8">
     <button type="button" class="btn btn-primary btn-lg btn-block"style="background-color: cadetblue"><a href="{% url 'contact:contact_form' %}"style="color: black;">添加联系人</a></button>
  <div class="row no-gutters">

         <div class="row">
{% for contact in contacts %}
  <div class="col-sm-4"style="padding-bottom: 10px;padding-left: 5px;padding-right: 5px;padding-top: 10px">
    <div class="card bg-light">
        <div class="card-header">姓名：{{ contact.name }}</div>
      <div class="card-body">
          <h5 class="card-title">关系：{{ contact.relation }}</h5>
          <h5 class="card-title">邮箱:{{ contact.email }}</h5>
          <h5 class="card-title">性别：{{ contact.get_sex_display  }}</h5>
          <h5 class="card-title">职业：{{ contact.word }}</h5>
          <h5 class="card-title">手机号：{{ contact.phone }}</h5>
        <p class="card-text"style="padding-top: 10px"><small class="text-muted">{{ contact.created_time }}</small></p>
           <a href="/delcontact/?id={{ contact.id }}"><button class="btn btn-primary">删除</button></a>
      </div>
    </div>

  </div>
{% endfor %}


</div>




  </div>
</div>



{% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>事务管理系统</title>
    {% block title %}{% endblock %}
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <script type="text/javascript" charset="utf-8" src="ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="ueditor.all.min.js"> </script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="lang/zh-cn/zh-cn.js"></script>

    <style type="text/css">
        div{
            width:100%;
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'js/index.css' %}">
  </head>
<style>
	.body-fonts{
        background-color: #e9ecef;
		font-family: 'fontawesome-webfont';

	}
</style>
<body class="body-fonts">

<nav class="navbar navbar-default sticky-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
            <span class="sr-only">切换导航条</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'password:index' %}"style="padding-bottom: 10px;padding-top: 10px;">主页</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if request.session.is_login %}
                  <li><a href="#"style="padding: 0px">欢迎：{{ request.session.user_name }}</a></li>
                  <li><a href="/logout/" style="padding: 0px">退出</a></li>
              {% else %}
                  <li><a href="/login/"style="padding: 0px">登录</a></li>
                  <li><a href="/register/"style="padding: 0px">注册</a></li>
              {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

<!--头部图-->
<div class="container">
    <div class="jumbotron jumbotron-fluid"style="background-color: cadetblue;height: 200px">
  <div class="container-fluid"style="text-align: center;padding-top: 10px">
    <h2 class="display-4">个人事务管理系统</h2>
  </div>

</div>


<div class="row">


<!--博主卡片-->
<div class="col-3">
<div class="card shadow p-3 mb-3 rounded">
  <img src="{% static 'img/324647.jpg' %}" class="img-rounded card-img-top">
  <div class="card-body card-text-color">
      <p class="card-text"><h5 style="color:dimgrey;"><strong>既然我已经踏上了这条道路，那么，任何东西都不应妨碍我沿着这条路走下去。</strong></h5></p>
  </div>
</div>
    <button type="button" class="btn btn-primary btn-lg btn-block shadow p-3 mb-3 rounded"><a href="{% url 'password:password' %}" style="color: black">密码管理</a></button>
    <button type="button" class="btn btn-primary btn-lg btn-block shadow p-3 mb-3 rounded"><a href="{% url 'myreport' %}" style="color: black">日程安排</a></button>
    <button type="button" class="btn btn-primary btn-lg btn-block shadow p-3 mb-3 rounded"><a href="{% url 'memo:memo_list' %}" style="color: black">便签</a></button>
    <button type="button" class="btn btn-primary btn-lg btn-block shadow p-3 mb-3 rounded"><a href="" style="color: black">账单</a></button>
    <button type="button" class="btn btn-primary btn-lg btn-block shadow p-3 mb-3 rounded"><a href="{% url 'image:image_list' %}" style="color: black">相册管理</a></button>
    <button type="button" class="btn btn-primary btn-lg btn-block shadow p-3 mb-3 rounded"><a href="{% url 'contact:contact_list' %}" style="color: black">联系人</a></button>
</div>

<!--内容-->
{% block main %}
     <div class="col-9 card shadow p-3 mb-3 rounded"style="padding-right: 0px;padding-left: 0px">

  <h5 class="card-header"style="background-color: cadetblue">最新密码</h5>
         <div class="row">
{% for password in passwords %}
  <div class="col-sm-6"style="padding-bottom: 30px;padding-left: 30px;padding-right: 30px;padding-top: 10px">
    <div class="card">
        <img src="/media/{{ password.image1 }}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ password.appname }}</h5>
        <p class="card-text">用户名：{{ password.user }}</p>
        <p class="card-text"><small class="text-muted">{{ password.created_time }}</small></p>
          <a href="{% url 'password:detail_password' password.id %}" class="btn btn-primary">more</a>
      </div>
    </div>

  </div>
{% endfor %}

</div>

           <h5 class="card-header"style="background-color: cadetblue">最新便签</h5>
         <div class="row ">
{% for memo in memos %}
  <div class="col-sm-6"style="padding-bottom: 30px;padding-left: 30px;padding-right: 30px;padding-top: 10px">
    <div class="card">
        <img src="/media/{{ memo.image2 }}" class="card-img-top" alt="...">
      <div class="card-body">
        <p class="card-text">{{ memo.category }}</p>
        <p class="card-text"><small class="text-muted">{{ memo.created_time }}</small></p>
          <a href="{% url 'memo:detail_memo' memo.id %}" class="btn btn-primary">more</a>
      </div>
    </div>

  </div>
{% endfor %}

</div>

<h5 class="card-header"style="background-color: cadetblue">最新照片</h5>
<div class="row">
{% for image in images %}
  <div class="col-sm-4"style="padding-bottom: 30px;padding-left: 30px;padding-right: 30px;padding-top: 10px">
    <div class="card">
        <img src="/media/{{ image.image3 }}" class="card-img-top" alt="...">
      <div class="card-body">
        <p class="card-text"><small class="text-muted">{{image.created_time }}</small></p>
      </div>
    </div>

  </div>
{% endfor %}

</div>


</div>
{% endblock %}


</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  </body>

</html>